### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by Suleman-Elahi** [remoteorigin/git-issues-downloader#16]
![image](https://user-images.githubusercontent.com/24384996/51658579-7baa6780-1fce-11e9-995f-c3888c2eca31.png)

**Comment by pavelbinar** [comment]
Hi @Suleman-Elahi ,

Thanks for reporting this error.
This error should not be platform specific. I made a fix and new release.

You can install new version [`v0.1.3`](https://github.com/remoteorigin/git-issues-downloader/releases/tag/v0.1.3) by:

```
npm install -g git-issues-downloader
```

Please test and let me know.


Thanks

**Comment by Suleman-Elahi** [comment]
Yeah..its working fine...thanks too.
![image](https://user-images.githubusercontent.com/24384996/52102116-b763b380-2604-11e9-8a82-8b12f66c22a2.png)
